Update map dependency
Switch to clang-format-14

diff --git a/.github/workflows/code_format_check.yml b/.github/workflows/code_format_check.yml
--- a/.github/workflows/code_format_check.yml
+++ b/.github/workflows/code_format_check.yml
@@ -14,7 +14,7 @@ jobs:
 
     name: Check Code Formatting
 
-    runs-on: ubuntu-20.04
+    runs-on: ubuntu-22.04
 
     steps:
     - name: Harden Runner
@@ -27,7 +27,7 @@ jobs:
           submodules: true
 
     - name: Install Dependencies
-      run: sudo apt-get update && sudo apt-get install clang-format-10
+      run: sudo apt-get update && sudo apt-get install clang-format-14
 
     - name: Check Formatting
-      run: failed=0; for file in `find . -path ./dependencies -prune -false -o -iname *.cpp -o -iname *.hpp`; do if [ `clang-format-10 $file -output-replacements-xml | grep -c "<replacement "` -ne 0 ]; then echo "$file does not match codeing style. Please run clang-format-10"; failed=1; fi; if [ $failed -ne 0 ]; then exit 1; fi; done
+      run: failed=0; for file in `find . -path ./dependencies -prune -false -o -iname *.cpp -o -iname *.hpp`; do if [ `clang-format-14 $file -output-replacements-xml | grep -c "<replacement "` -ne 0 ]; then echo "$file does not match codeing style. Please run clang-format-14"; failed=1; fi; if [ $failed -ne 0 ]; then exit 1; fi; done
