Switched to clang-format-10
Change-Id: I3623f7c836804b11cb47db1094c4b5e077af44b6

diff --git a/.github/workflows/code_format_check.yml b/.github/workflows/code_format_check.yml
--- a/.github/workflows/code_format_check.yml
+++ b/.github/workflows/code_format_check.yml
@@ -11,7 +11,7 @@ jobs:
 
     name: Check Code Formatting
 
-    runs-on: ubuntu-16.04
+    runs-on: ubuntu-20.04
 
     steps:
     - uses: actions/checkout@v2
@@ -19,7 +19,7 @@ jobs:
           submodules: true
 
     - name: Install Dependencies
-      run: sudo apt-get update && sudo apt-get install clang-format-3.9
+      run: sudo apt-get update && sudo apt-get install clang-format-10
 
     - name: Check Formatting
-      run: failed=0; for file in `find . -path ./dependencies -prune -false -o -iname *.cpp -o -iname *.hpp`; do if [ `clang-format-3.9 $file -output-replacements-xml | grep -c "<replacement "` -ne 0 ]; then echo "$file does not match codeing style. Please run clang-format-3.9"; failed=1; fi; if [ $failed -ne 0 ]; then exit 1; fi; done
+      run: failed=0; for file in `find . -path ./dependencies -prune -false -o -iname *.cpp -o -iname *.hpp`; do if [ `clang-format-10 $file -output-replacements-xml | grep -c "<replacement "` -ne 0 ]; then echo "$file does not match codeing style. Please run clang-format-10"; failed=1; fi; if [ $failed -ne 0 ]; then exit 1; fi; done
